### ISSUE TITLE
id

### ISSUE THREAD

**Issue by EmilyJab** [c4cs/c4cs.github.io#54]

**Comment by the-alex** [comment]
Hey, I just want to let you know that someone else has made a PR for `id`. Now, you filed an issue first, so you have a right to the command, however, it has been 5 days since you filed the issue and you haven't made a PR yet.

The other student has finished their `id` commit, so if you don't finish yours in the next day or so, we'll have to close this issue and let the other student take the `id` command.

**Comment by the-alex** [comment]
@EmilyJab
