### ISSUE TITLE
t

### ISSUE THREAD

**Issue by alexandertmills** [c4cs/c4cs.github.io#88]
Command line client for browsing twitter. Documentation coming.

**Comment by ppannuto** [comment]
Cool -- as a 3rd party thing, make sure that you also include some basic
pointers for how to install it :)

> On Mar 20 2016, at 3:40 pm, alexandertmills &lt;notifications@github.com&gt;
wrote:  

>

> Command line client for browsing twitter. Documentation coming.

>

> —  
You are receiving this because you are subscribed to this thread.  
Reply to this email directly or [view it on GitHub](https://github.com/c4cs/c4
cs.github.io/issues/88)![](https://github.com/notifications/beacon
/AAUt3pmQuUFVINZsEd722oH4rNMfAHl-ks5pvaKUgaJpZM4H0vm0.gif)

**Comment by alexandertmills** [comment]
Will do!

Alexander Mills
atmills@umich.edu
